import {
  Habit,
  BadHabit,
  ScheduleTask,
  DailyVitals,
  RewardItem,
  GoldenVault,
  TimeCapsule,
  Achievement,
  UserEconomy,
  UserSettings,
  DifficultyConfig,
  DifficultyMode,
  StreakState,
  RecoveryStats,
  LoopIncident,
  DisciplineTimeframeGoal,
  PersonalGoal,
  EconomyTransaction,
  ActivityLogItem,
} from '../types';

export const getTodayKey = (customDate?: Date | string): string => {
  if (typeof customDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(customDate)) {
    return customDate;
  }
  const d = customDate instanceof Date ? customDate : new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const getPastDateKey = (daysAgo: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const getFutureDateKey = (daysAhead: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const DIFFICULTY_CONFIGS: Record<DifficultyMode, DifficultyConfig> = {
  easy: {
    mode: 'easy',
    title: 'Balanced Explorer',
    description: 'Gentle progression with relaxed goal thresholds and generous rewards.',
    coinMultiplier: 1.25,
    xpMultiplier: 1.2,
    penaltyMultiplier: 0.5,
    dailyGoalFactor: 0.75,
    rewardCostMultiplier: 0.85,
  },
  normal: {
    mode: 'normal',
    title: 'Disciplined Monk',
    description: 'The standard LifeOS experience. Fair, balanced, and sustainable.',
    coinMultiplier: 1.0,
    xpMultiplier: 1.0,
    penaltyMultiplier: 1.0,
    dailyGoalFactor: 1.0,
    rewardCostMultiplier: 1.0,
  },
  hard: {
    mode: 'hard',
    title: 'High Performer',
    description: 'Strict standards. Higher rewards for consistency, higher penalty on misses.',
    coinMultiplier: 1.5,
    xpMultiplier: 1.4,
    penaltyMultiplier: 1.5,
    dailyGoalFactor: 1.2,
    rewardCostMultiplier: 1.25,
  },
  extreme: {
    mode: 'extreme',
    title: 'Spartan Architect',
    description: 'Extreme accountability. Low tolerance for missed schedules.',
    coinMultiplier: 2.0,
    xpMultiplier: 1.8,
    penaltyMultiplier: 2.0,
    dailyGoalFactor: 1.4,
    rewardCostMultiplier: 1.5,
  },
  hardcore: {
    mode: 'hardcore',
    title: 'Absolute Savage',
    description: 'Ironclad mode. Relapses trigger token freezing and maximum discipline pressure.',
    coinMultiplier: 3.0,
    xpMultiplier: 2.5,
    penaltyMultiplier: 3.0,
    dailyGoalFactor: 1.6,
    rewardCostMultiplier: 2.0,
  },
};

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'h-1',
    name: 'Cold Shower & Wim Hof Breath',
    icon: 'Droplets',
    color: '#06B6D4',
    category: 'Health',
    reminder: '06:30',
    frequency: 'daily',
    difficulty: 'medium',
    coinReward: 25,
    xpReward: 50,
    notes: '3 min freezing cold + 3 rounds breathing.',
    streak: 6,
    longestStreak: 18,
    completedDates: [getPastDateKey(1), getPastDateKey(2), getPastDateKey(3), getPastDateKey(4), getPastDateKey(5), getPastDateKey(6)],
  },
  {
    id: 'h-2',
    name: '90-Min Deep Work Block',
    icon: 'Cpu',
    color: '#F59E0B',
    category: 'Productivity',
    reminder: '09:00',
    frequency: 'daily',
    difficulty: 'hard',
    coinReward: 60,
    xpReward: 120,
    notes: 'Zero tabs, phone in another room, single-tasking.',
    streak: 4,
    longestStreak: 14,
    completedDates: [getPastDateKey(1), getPastDateKey(2), getPastDateKey(3), getPastDateKey(4)],
  },
  {
    id: 'h-3',
    name: 'Hypertrophy Workout / 10k Steps',
    icon: 'Dumbbell',
    color: '#EF4444',
    category: 'Fitness',
    reminder: '17:00',
    frequency: 'daily',
    difficulty: 'hard',
    coinReward: 50,
    xpReward: 100,
    notes: 'Push to failure with good form.',
    streak: 12,
    longestStreak: 21,
    completedDates: [getPastDateKey(1), getPastDateKey(2), getPastDateKey(3), getPastDateKey(4), getPastDateKey(5), getPastDateKey(6), getPastDateKey(7)],
  },
  {
    id: 'h-4',
    name: 'Read 20 Pages Non-Fiction',
    icon: 'BookOpen',
    color: '#8B5CF6',
    category: 'Learning',
    reminder: '21:00',
    frequency: 'daily',
    difficulty: 'easy',
    coinReward: 30,
    xpReward: 60,
    notes: 'Highlight key takeaways into second brain.',
    streak: 8,
    longestStreak: 30,
    completedDates: [getPastDateKey(1), getPastDateKey(2), getPastDateKey(3), getPastDateKey(4), getPastDateKey(5), getPastDateKey(6), getPastDateKey(7), getPastDateKey(8)],
  },
  {
    id: 'h-5',
    name: 'Evening Reflection & Shutdown',
    icon: 'Moon',
    color: '#10B981',
    category: 'Mindset',
    reminder: '22:30',
    frequency: 'daily',
    difficulty: 'easy',
    coinReward: 20,
    xpReward: 40,
    notes: 'Review Day Score, schedule tomorrow, no screens 30m before bed.',
    streak: 5,
    longestStreak: 12,
    completedDates: [getPastDateKey(1), getPastDateKey(2), getPastDateKey(3), getPastDateKey(4), getPastDateKey(5)],
  },
];

export const INITIAL_BAD_HABITS: BadHabit[] = [
  {
    id: 'bh-1',
    name: 'Doomscrolling Shorts / Reels',
    icon: 'SmartphoneOff',
    color: '#EF4444',
    quitDate: getPastDateKey(14),
    challengeDaysTarget: 21,
    currentStreakDays: 14,
    longestStreakDays: 14,
    relapseCount: 1,
    relapses: [
      {
        id: 'rel-1',
        date: getPastDateKey(15),
        time: '23:15',
        reason: 'Late night boredom and tired willpower',
        notes: 'Installed blocker app immediately after.',
      },
    ],
    successPercentage: 93,
    recoveryBonusEligible: true,
    cleanDaysHistory: Array.from({ length: 14 }, (_, i) => getPastDateKey(i + 1)),
  },
  {
    id: 'bh-2',
    name: 'Late-Night Sugary Snacking',
    icon: 'Cookie',
    color: '#F97316',
    quitDate: getPastDateKey(9),
    challengeDaysTarget: 21,
    currentStreakDays: 9,
    longestStreakDays: 16,
    relapseCount: 2,
    relapses: [
      {
        id: 'rel-2',
        date: getPastDateKey(10),
        time: '22:45',
        reason: 'Stress eating after long project deadline',
        notes: 'Replaced with herbal chamomile tea.',
      },
      {
        id: 'rel-3',
        date: getPastDateKey(27),
        time: '23:00',
        reason: 'Social gathering leftovers',
      },
    ],
    successPercentage: 88,
    recoveryBonusEligible: true,
    cleanDaysHistory: Array.from({ length: 9 }, (_, i) => getPastDateKey(i + 1)),
  },
  {
    id: 'bh-3',
    name: 'Snoozing Morning Alarm',
    icon: 'AlarmClockOff',
    color: '#EC4899',
    quitDate: getPastDateKey(19),
    challengeDaysTarget: 21,
    currentStreakDays: 19,
    longestStreakDays: 19,
    relapseCount: 0,
    relapses: [],
    successPercentage: 100,
    recoveryBonusEligible: true,
    cleanDaysHistory: Array.from({ length: 19 }, (_, i) => getPastDateKey(i + 1)),
  },
];

export const INITIAL_SCHEDULE: ScheduleTask[] = [
  {
    id: 'task-1',
    title: 'Morning Protocol & Hydration',
    timeSlot: 'morning',
    startTime: '06:30',
    endTime: '07:15',
    category: 'routine',
    priority: 'high',
    repeat: 'daily',
    completed: true,
    date: getTodayKey(),
    durationMinutes: 45,
  },
  {
    id: 'task-2',
    title: 'Deep Architecture & Core Coding Block',
    timeSlot: 'morning',
    startTime: '08:30',
    endTime: '11:30',
    category: 'deep_work',
    priority: 'high',
    repeat: 'weekdays',
    completed: true,
    date: getTodayKey(),
    durationMinutes: 180,
  },
  {
    id: 'task-3',
    title: 'Executive Inbox & Team Syncs',
    timeSlot: 'afternoon',
    startTime: '13:00',
    endTime: '14:30',
    category: 'personal',
    priority: 'medium',
    repeat: 'weekdays',
    completed: false,
    date: getTodayKey(),
    durationMinutes: 90,
  },
  {
    id: 'task-4',
    title: 'System Design & Research',
    timeSlot: 'afternoon',
    startTime: '15:00',
    endTime: '16:30',
    category: 'learning',
    priority: 'medium',
    repeat: 'none',
    completed: false,
    date: getTodayKey(),
    durationMinutes: 90,
  },
  {
    id: 'task-5',
    title: 'Strength Training Session',
    timeSlot: 'evening',
    startTime: '17:30',
    endTime: '18:45',
    category: 'health',
    priority: 'high',
    repeat: 'daily',
    completed: false,
    date: getTodayKey(),
    durationMinutes: 75,
  },
  {
    id: 'task-6',
    title: 'Reading & Wind-down Routine',
    timeSlot: 'night',
    startTime: '21:30',
    endTime: '22:30',
    category: 'recovery',
    priority: 'medium',
    repeat: 'daily',
    completed: false,
    date: getTodayKey(),
    durationMinutes: 60,
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'rew-1',
    name: 'Double Wagyu Smash Burger',
    icon: 'UtensilsCrossed',
    description: 'Guilt-free gourmet feast with truffle fries after hitting weekly discipline.',
    coinCost: 180,
    category: 'Food',
    difficulty: 'medium',
    isAvailable: true,
    timesPurchased: 4,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'rew-2',
    name: '2-Hour PS5 / PC Gaming Session',
    icon: 'Gamepad2',
    description: 'Uninterrupted immersive gaming with zero guilt or schedule anxiety.',
    coinCost: 120,
    category: 'Entertainment',
    difficulty: 'easy',
    isAvailable: true,
    timesPurchased: 9,
    imageUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'rew-3',
    name: '1-Hour Guilt-Free YouTube Pass',
    icon: 'Tv',
    description: 'Watch documentaries, tech reviews, or podcasts during scheduled leisure.',
    coinCost: 60,
    category: 'Entertainment',
    difficulty: 'easy',
    isAvailable: true,
    timesPurchased: 15,
  },
  {
    id: 'rew-4',
    name: 'Premium Leather Notebook & Pen',
    icon: 'PenTool',
    description: 'High quality Japanese stationery to elevate thinking and system journaling.',
    coinCost: 350,
    category: 'Shopping',
    difficulty: 'hard',
    isAvailable: true,
    timesPurchased: 1,
  },
  {
    id: 'rew-5',
    name: 'High-End Noise-Canceling Headphones',
    icon: 'Headphones',
    description: 'Flagship audio gear reward for sustaining 30-day streak unbroken.',
    coinCost: 1500,
    category: 'Luxury',
    difficulty: 'legendary',
    isAvailable: true,
    timesPurchased: 0,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'rew-6',
    name: 'Weekend Mountain Cabin Getaway',
    icon: 'Compass',
    description: 'Off-grid 48-hour nature reset after completing quarterly mission milestones.',
    coinCost: 2800,
    category: 'Travel',
    difficulty: 'legendary',
    isAvailable: true,
    timesPurchased: 0,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_VAULTS: GoldenVault[] = [
  {
    id: 'vault-1',
    name: 'Sovereign 30-Day Master Certificate',
    depositCoins: 400,
    termDays: 30,
    startDate: getPastDateKey(12),
    maturityDate: getPastDateKey(-18),
    baseInterestRate: 0.35,
    initialMultiplier: 1.35,
    currentMultiplier: 1.55,
    disciplineMultiplier: 1.25,
    disciplineTier: 'high',
    dailyGrowthCoins: 7,
    currentValue: 488,
    expectedMaturityValue: 620,
    avgDayScoreSnapshot: 86,
    status: 'growing',
    reinvestCount: 0,
    isTimeCapsule: false,
  },
  {
    id: 'vault-2',
    name: '7-Day High-Velocity Sprint Vault',
    depositCoins: 250,
    termDays: 7,
    startDate: getPastDateKey(7),
    maturityDate: getTodayKey(),
    baseInterestRate: 0.12,
    initialMultiplier: 1.12,
    currentMultiplier: 1.28,
    disciplineMultiplier: 1.5,
    disciplineTier: 'maximum',
    dailyGrowthCoins: 10,
    currentValue: 320,
    expectedMaturityValue: 320,
    avgDayScoreSnapshot: 93,
    status: 'matured',
    reinvestCount: 1,
    isTimeCapsule: false,
  },
];

export const INITIAL_CAPSULES: TimeCapsule[] = [
  {
    id: 'cap-1',
    title: 'Ascension to 50-Day Unbroken Streak',
    futureMessage: 'If you are reading this, you conquered resistance. The version of you that locked these 500 coins was doubtful, but you proved discipline is your identity.',
    personalPromise: 'I promise to complete morning breathwork and maintain my workout habit every single day without excuses.',
    goal: 'Maintain unbroken habit streaks & complete 100 focus hours',
    rewardDescription: 'Unlock locked treasure + 250 bonus discipline coins + Master title',
    startDate: getPastDateKey(35),
    targetDate: getPastDateKey(-15),
    lockedCoins: 500,
    createdAt: getPastDateKey(35),
    isUnlocked: false,
    bonusCoinsEarned: 250,
    disciplineMultiplierBonus: 1.5,
    photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Step to Mastery',
    description: 'Complete your first habit with 100% focus.',
    category: 'Habits',
    icon: 'Sparkles',
    progress: 1,
    maxProgress: 1,
    isUnlocked: true,
    unlockedDate: getPastDateKey(30),
    coinReward: 50,
    xpReward: 100,
    claimed: true,
    tier: 'bronze',
  },
  {
    id: 'ach-2',
    title: 'Titan of Deep Work',
    description: 'Accumulate 50 total hours of deep work focus sessions.',
    category: 'Focus',
    icon: 'Zap',
    progress: 38,
    maxProgress: 50,
    isUnlocked: false,
    coinReward: 200,
    xpReward: 400,
    claimed: false,
    tier: 'gold',
  },
  {
    id: 'ach-3',
    title: 'The 21-Day Demon Slayer',
    description: 'Destroy a bad habit by sustaining a 21-day clean streak.',
    category: 'Discipline',
    icon: 'ShieldCheck',
    progress: 19,
    maxProgress: 21,
    isUnlocked: false,
    coinReward: 350,
    xpReward: 700,
    claimed: false,
    tier: 'platinum',
  },
  {
    id: 'ach-4',
    title: 'Monk Mindset',
    description: 'Log 7 consecutive days with a Day Score above 85.',
    category: 'Discipline',
    icon: 'Flame',
    progress: 5,
    maxProgress: 7,
    isUnlocked: false,
    coinReward: 300,
    xpReward: 600,
    claimed: false,
    tier: 'diamond',
  },
  {
    id: 'ach-5',
    title: 'Iron Sleep Protocol',
    description: 'Log 7+ hours of quality sleep for 14 consecutive nights.',
    category: 'Sleep',
    icon: 'MoonStar',
    progress: 9,
    maxProgress: 14,
    isUnlocked: false,
    coinReward: 180,
    xpReward: 350,
    claimed: false,
    tier: 'silver',
  },
  {
    id: 'ach-6',
    title: 'Literary Giant',
    description: 'Read over 500 cumulative pages in tracked habits.',
    category: 'Reading',
    icon: 'BookOpenCheck',
    progress: 340,
    maxProgress: 500,
    isUnlocked: false,
    coinReward: 250,
    xpReward: 500,
    claimed: false,
    tier: 'gold',
  },
  {
    id: 'ach-7',
    title: 'Golden Vault Sovereign',
    description: 'Successfully mature and harvest a high-discipline Golden Token vault.',
    category: 'Special',
    icon: 'Award',
    progress: 25,
    maxProgress: 30,
    isUnlocked: false,
    coinReward: 400,
    xpReward: 800,
    claimed: false,
    tier: 'obsidian',
  },
];

export const INITIAL_VITALS: DailyVitals = {
  date: getTodayKey(),
  mood: 4,
  sleepHours: 7.5,
  sleepQuality: 4,
  waterGlasses: 5,
  waterTarget: 8,
  energyLevel: 4,
  screenTimeMinutes: 140,
  workoutMinutes: 45,
  journalText: 'Woke up energized. Completed morning breathwork and deep code block without distraction.',
  morningMission: 'Ship core OS architecture & maintain laser focus',
  recoveryMission: '',
  manualScoreOverride: null,
};

export const INITIAL_ECONOMY: UserEconomy = {
  coins: 1000,
  lifetimeEarned: 3850,
  lifetimeSpent: 2850,
  goldenTokens: 4,
  xp: 5600,
  level: 12,
  lifetimeXP: 5600,
  highestLevel: 12,
  unlockedTitles: ['Beginner', 'Explorer', 'Disciplined'],
  activeTitle: 'Disciplined',
};

export const INITIAL_SETTINGS: UserSettings = {
  difficulty: 'normal',
  theme: 'black',
  goldAccent: true,
  glassIntensity: 0.75,
  soundEnabled: true,
  hapticsEnabled: true,
  notificationsEnabled: true,
  userName: 'Commander',
  userTitle: 'Commander',
  nameTemplate: '{title}',
  avatarSeed: 'lifeos-avatar-1',
  timeSyncMode: 'auto',
};

export const INITIAL_STREAK: StreakState = {
  currentStreak: 12,
  longestStreak: 18,
  lastActiveDate: getTodayKey(),
  todayClaimed: true,
  totalCoinsEarned: 360,
  streakHistory: Array.from({ length: 12 }, (_, i) => getPastDateKey(i)),
};

export const INITIAL_RECOVERY_STATS: RecoveryStats = {
  currentRecoveryStreak: 5,
  fastestRecoveryDays: 1.0,
  averageRecoveryDays: 1.4,
  recoverySuccessRate: 92,
  totalLoopsInterrupted: 7,
};

export const INITIAL_LOOP_INCIDENTS: LoopIncident[] = [
  {
    id: 'loop-1',
    date: getPastDateKey(2),
    time: '21:30',
    triggerReason: 'YouTube',
    notes: 'Got trapped in rabbit hole after dinner.',
    microActionChosen: 'Drink one glass of cold water and do 10 deep breaths',
    completedRescueTimer: true,
    rescueDurationSeconds: 300,
    recoveredAtDate: getPastDateKey(1),
    recoveryDaysTaken: 1,
  },
  {
    id: 'loop-2',
    date: getPastDateKey(8),
    time: '15:45',
    triggerReason: 'Low Energy',
    notes: 'Afternoon fatigue spike after heavy meal.',
    microActionChosen: 'Stand up and walk for 2 minutes',
    completedRescueTimer: true,
    rescueDurationSeconds: 300,
    recoveredAtDate: getPastDateKey(7),
    recoveryDaysTaken: 1,
  },
];

export const INITIAL_TIMEFRAME_GOALS: DisciplineTimeframeGoal[] = [
  // Daily Goals
  {
    id: 'dtg-1',
    timeframe: 'daily',
    title: '100% Core Habits Completion',
    targetMetric: 'Completed Habits',
    currentValue: 4,
    targetValue: 4,
    unit: 'habits',
    completed: true,
    rewardCoins: 25,
    rewardXP: 50,
    category: 'Habits',
  },
  {
    id: 'dtg-2',
    timeframe: 'daily',
    title: 'Laser Focus Deep Work',
    targetMetric: 'Focus Time',
    currentValue: 90,
    targetValue: 90,
    unit: 'min',
    completed: true,
    rewardCoins: 30,
    rewardXP: 60,
    category: 'Focus',
  },
  {
    id: 'dtg-3',
    timeframe: 'daily',
    title: 'Clean Day Standard (Zero Relapse)',
    targetMetric: 'Clean Standards',
    currentValue: 3,
    targetValue: 3,
    unit: 'tracks',
    completed: true,
    rewardCoins: 35,
    rewardXP: 70,
    category: 'Clean Living',
  },
  {
    id: 'dtg-4',
    timeframe: 'daily',
    title: 'Optimal Hydration Protocol',
    targetMetric: 'Water Intake',
    currentValue: 6,
    targetValue: 8,
    unit: 'glasses',
    completed: false,
    rewardCoins: 15,
    rewardXP: 30,
    category: 'Fitness',
  },

  // Weekly Goals
  {
    id: 'dtg-w1',
    timeframe: 'weekly',
    title: '5x Intense Physical Conditioning',
    targetMetric: 'Workouts Completed',
    currentValue: 4,
    targetValue: 5,
    unit: 'sessions',
    completed: false,
    rewardCoins: 100,
    rewardXP: 200,
    category: 'Fitness',
  },
  {
    id: 'dtg-w2',
    timeframe: 'weekly',
    title: '15 Hours High-Output Deep Work',
    targetMetric: 'Deep Work Hours',
    currentValue: 12.5,
    targetValue: 15,
    unit: 'hours',
    completed: false,
    rewardCoins: 150,
    rewardXP: 300,
    category: 'Focus',
  },
  {
    id: 'dtg-w3',
    timeframe: 'weekly',
    title: 'Zero Relapse Flawless Week',
    targetMetric: 'Clean Days',
    currentValue: 7,
    targetValue: 7,
    unit: 'days',
    completed: true,
    rewardCoins: 200,
    rewardXP: 350,
    category: 'Clean Living',
  },
  {
    id: 'dtg-w4',
    timeframe: 'weekly',
    title: '90+ Average Day Score Velocity',
    targetMetric: 'Avg Day Score',
    currentValue: 91.2,
    targetValue: 90,
    unit: 'pts',
    completed: true,
    rewardCoins: 120,
    rewardXP: 250,
    category: 'Mindset',
  },

  // Monthly Goals
  {
    id: 'dtg-m1',
    timeframe: 'monthly',
    title: '30-Day Golden Vault Maturity',
    targetMetric: 'Vault Certificates',
    currentValue: 1,
    targetValue: 1,
    unit: 'vaults',
    completed: true,
    rewardCoins: 400,
    rewardXP: 800,
    category: 'Finances',
  },
  {
    id: 'dtg-m2',
    timeframe: 'monthly',
    title: '20+ Perfect S-Tier Days (Score ≥ 90)',
    targetMetric: 'S-Tier Days',
    currentValue: 16,
    targetValue: 20,
    unit: 'days',
    completed: false,
    rewardCoins: 350,
    rewardXP: 700,
    category: 'Mindset',
  },
  {
    id: 'dtg-m3',
    timeframe: 'monthly',
    title: 'Read 2 Sovereign Philosophy Books',
    targetMetric: 'Books Finished',
    currentValue: 1,
    targetValue: 2,
    unit: 'books',
    completed: false,
    rewardCoins: 250,
    rewardXP: 500,
    category: 'Focus',
  },

  // Yearly Vision Targets
  {
    id: 'dtg-y1',
    timeframe: 'yearly',
    title: '300+ Clean Sovereign Days Unbroken',
    targetMetric: 'Total Clean Days',
    currentValue: 118,
    targetValue: 300,
    unit: 'days',
    completed: false,
    rewardCoins: 2500,
    rewardXP: 5000,
    category: 'Clean Living',
  },
  {
    id: 'dtg-y2',
    timeframe: 'yearly',
    title: '500+ Hours Documented Deep Work',
    targetMetric: 'Deep Work Hours',
    currentValue: 215,
    targetValue: 500,
    unit: 'hours',
    completed: false,
    rewardCoins: 3000,
    rewardXP: 6000,
    category: 'Focus',
  },
  {
    id: 'dtg-y3',
    timeframe: 'yearly',
    title: 'Ascend to Level 50 Elite Sovereign Rank',
    targetMetric: 'RPG Level',
    currentValue: 12,
    targetValue: 50,
    unit: 'level',
    completed: false,
    rewardCoins: 5000,
    rewardXP: 10000,
    category: 'Mindset',
  },
  {
    id: 'dtg-y4',
    timeframe: 'yearly',
    title: 'Mine 25 Golden Tokens into Vaults',
    targetMetric: 'Golden Tokens',
    currentValue: 4,
    targetValue: 25,
    unit: 'tokens',
    completed: false,
    rewardCoins: 4000,
    rewardXP: 8000,
    category: 'Finances',
  },
];

export const INITIAL_GOALS: PersonalGoal[] = [
  {
    id: 'goal-1',
    title: 'Achieve 30-Day Relapse-Free Discipline Streak',
    description: 'Eliminate digital distractions, maintain unbroken focus, and build unbreakable habit consistency.',
    category: 'Mindset & Discipline',
    priority: 'critical',
    targetDate: getFutureDateKey(16),
    progress: 47,
    status: 'in_progress',
    relatedHabits: ['Morning Cold Shower & Hydration', 'Night Reflection & Digital Blackout'],
    rewardOnCompletion: {
      coins: 500,
      xp: 1000,
      customRewardText: '100% Unlocked Sovereign Tier Badge',
    },
    notes: 'Stay vigilant during late evenings. Keep phone outside bedroom.',
    icon: 'Flame',
    createdAt: getPastDateKey(14),
  },
  {
    id: 'goal-2',
    title: 'Complete 100 Hours of High-Output Deep Work',
    description: 'Execute deep focused coding and architectural development blocks with zero context-switching.',
    category: 'Career & Wealth',
    priority: 'high',
    targetDate: getFutureDateKey(25),
    progress: 68,
    status: 'in_progress',
    relatedHabits: ['Deep Work Block (2h)'],
    rewardOnCompletion: {
      coins: 350,
      xp: 750,
      customRewardText: 'High-Output Mastery Certificate',
    },
    notes: 'Document all session metrics into the Sovereign Bank vault.',
    icon: 'Zap',
    createdAt: getPastDateKey(20),
  },
  {
    id: 'goal-3',
    title: 'Read 10 Mastery & Cognitive Science Books',
    description: 'Study mental models, neuroscience, stoic philosophy, and deep habit psychology.',
    category: 'Learning & Skills',
    priority: 'medium',
    targetDate: getFutureDateKey(45),
    progress: 40,
    status: 'in_progress',
    relatedHabits: ['Read 20 Pages of Non-Fiction'],
    rewardOnCompletion: {
      coins: 250,
      xp: 500,
    },
    notes: 'Currently finishing Atomic Habits and Meditations.',
    icon: 'BookOpen',
    createdAt: getPastDateKey(30),
  },
  {
    id: 'goal-4',
    title: 'Run 10km in Sub-45 Minutes',
    description: 'Progressive cardio conditioning, aerobic base building, and VO2 max improvement.',
    category: 'Health & Fitness',
    priority: 'high',
    targetDate: getFutureDateKey(30),
    progress: 75,
    status: 'in_progress',
    relatedHabits: ['Daily Physical Conditioning (45m)'],
    rewardOnCompletion: {
      coins: 300,
      xp: 600,
      customRewardText: 'Sub-45 Athlete Recognition',
    },
    notes: 'Pacing at 4:38/km currently. Need 2 more interval track sessions.',
    icon: 'Dumbbell',
    createdAt: getPastDateKey(25),
  },
  {
    id: 'goal-5',
    title: 'Establish 5:30 AM Morning Routine Protocol',
    description: 'Wake up consistently at 5:30 AM without alarm snooze, hydrate, and complete cold exposure.',
    category: 'Personal & Lifestyle',
    priority: 'medium',
    targetDate: getPastDateKey(2),
    progress: 100,
    status: 'completed',
    relatedHabits: ['Morning Cold Shower & Hydration'],
    rewardOnCompletion: {
      coins: 200,
      xp: 400,
    },
    notes: 'Seamlessly achieved 21 days straight without a single miss.',
    icon: 'Target',
    createdAt: getPastDateKey(30),
    completedAt: getPastDateKey(2),
  },
];

export const INITIAL_TRANSACTIONS: EconomyTransaction[] = [
  {
    id: 'tx-1',
    type: 'earn',
    amount: 30,
    label: 'Daily Streak Check-in Bonus',
    category: 'Streak',
    timestamp: 'Today • 08:30 AM',
    createdAt: Date.now() - 1000 * 60 * 60 * 3,
  },
  {
    id: 'tx-2',
    type: 'earn',
    amount: 35,
    label: 'Completed Habit: Cold Shower & Wim Hof',
    category: 'Health',
    timestamp: 'Today • 09:15 AM',
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: 'tx-3',
    type: 'earn',
    amount: 30,
    label: 'Deep Work Focus Session (25m)',
    category: 'Focus',
    timestamp: 'Today • 10:45 AM',
    createdAt: Date.now() - 1000 * 60 * 60,
  },
  {
    id: 'tx-4',
    type: 'spend',
    amount: 50,
    label: 'Redeemed: Specialty Artisan Espresso',
    category: 'Reward',
    timestamp: 'Today • 11:20 AM',
    createdAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: 'tx-5',
    type: 'earn',
    amount: 35,
    label: 'Clean Day Mastered: Doomscrolling',
    category: 'Discipline',
    timestamp: 'Today • 11:55 AM',
    createdAt: Date.now() - 1000 * 60 * 10,
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLogItem[] = [
  {
    id: 'act-1',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    date: getTodayKey(),
    time: '11:55:00',
    category: 'Bad Habits',
    relatedFeature: '21-Day Clean Shield',
    eventTitle: 'Clean Day Mastered: Doomscrolling',
    description: 'Maintained unbroken sovereign shield against short-form algorithmic loops.',
    icon: 'ShieldCheck',
    coinsChange: 35,
    xpChange: 60,
    badgeColor: 'emerald',
  },
  {
    id: 'act-2',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    date: getTodayKey(),
    time: '11:20:00',
    category: 'Economy',
    relatedFeature: 'Reward Shop',
    eventTitle: 'Reward Claimed: Specialty Artisan Espresso',
    description: 'Redeemed earned discipline coins for a guilt-free sensory recharge.',
    icon: 'Gift',
    coinsChange: -50,
    badgeColor: 'amber',
  },
  {
    id: 'act-3',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    date: getTodayKey(),
    time: '10:45:00',
    category: 'Focus',
    relatedFeature: 'Deep Work Protocol',
    eventTitle: 'Focus Session Completed (25 min)',
    description: 'Completed uninterrupted deep flow block on core quarterly project architecture.',
    icon: 'Clock',
    coinsChange: 30,
    xpChange: 50,
    badgeColor: 'cyan',
  },
  {
    id: 'act-4',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    date: getTodayKey(),
    time: '09:15:00',
    category: 'Habits',
    relatedFeature: 'Keystone Habit',
    eventTitle: 'Habit Completed: Cold Shower & Wim Hof',
    description: 'Triggered metabolic activation and neurochemical resilience protocol.',
    icon: 'Droplets',
    coinsChange: 35,
    xpChange: 70,
    badgeColor: 'cyan',
  },
  {
    id: 'act-5',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    date: getTodayKey(),
    time: '08:30:00',
    category: 'System',
    relatedFeature: 'Daily Streak Engine',
    eventTitle: 'Daily Discipline Streak Logged (Day 12)',
    description: 'Checked into LifeOS Sovereign Command Center and preserved unbroken streak.',
    icon: 'Flame',
    coinsChange: 30,
    xpChange: 40,
    badgeColor: 'amber',
  },
];



